baseURL = "https://blog.silverwis.com"
languageCode = "ko-kr"
title = "lifeviewer"
copyright = "ìµœì‹  ì •ë³´"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  env = "production"
  title = "lifeview"
  description = "ëˆ„êµ¬ë‚˜ ì‰½ê²Œ ì°¾ëŠ” ë³µì§€ í˜œíƒ ì •ë³´"
  
  # Google AdSense ID
  googleAdsense = "ca-pub-1279348640476088"
  
  # ê¸°ë³¸ ì„¤ì •ë“¤
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  
  # ê²€ìƒ‰ ì„¤ì •
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "home"
  name = "ğŸ  í™ˆ"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "categories"
  name = "ğŸ“‚ ì¹´í…Œê³ ë¦¬"
  url = "/categories/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "ğŸ” ê²€ìƒ‰"
  url = "/search/"
  weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
